### ISSUE TITLE
run gulp, receive blank page

### ISSUE THREAD

**Issue by daiyiwhale** [Trustroots/trustroots#319]
Clean installation: did the instructions [here](https://github.com/Trustroots/trustroots/blob/master/INSTALL.md), ran `gulp`, got these errors:

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'run-sequence'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/kujira/Documents/trustroots/gulpfile.js:11:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

Fixed with a quick `npm install run-sequence` (maybe needs some shrinkwrap? (: ).

gulp now runs smoothly, but other than page title and favicon `localhost:3000` is a blank page. No browser errors, gulp reports assets are being served and all. I can see the dom in my developer console. Page is still blank. Whaat. Maybe this is an issue with angular?

**Comment by simison** [comment]
Thanks, I'll add missing run-sequence to packages.

`gulp` task is still totally under construction — do you get it running with `grunt`?

**Comment by simison** [comment]
Gulp tasks should now work much better, although preferred way of running the app now on localhost is `npm start`.

Wanna test our new Docker setup? :-)
https://github.com/Trustroots/trustroots/blob/master/INSTALL-DOCKER.md

Local install instructions:
https://github.com/Trustroots/trustroots/blob/master/INSTALL.md
