### ISSUE TITLE
Update to MongoDB 3.2

### ISSUE THREAD

**Issue by simison** [Trustroots/trustroots#338]
Currently running 2.x

https://www.mongodb.com/mongodb-3.2

Might require changes to tests/code at least due changes in unique field errors.

**Comment by simison** [comment]
Also make sure to lock down the version here: https://github.com/Trustroots/trustroots/blob/master/docker-compose.yml#L46

**Comment by simison** [comment]
[Agenda](https://github.com/rschmukler/agenda) might not support 3.2 yet.

**Comment by simison** [comment]
This needs fixing:

```
trustroots_1 | /trustroots/node_modules/mongoose/node_modules/mongodb/lib/utils.js:98
trustroots_1 |     process.nextTick(function() { throw err; });
trustroots_1 |                                   ^
trustroots_1 | 
trustroots_1 | TypeError: Cannot read property '1' of null
trustroots_1 |     at beautify (/trustroots/node_modules/mongoose-beautiful-unique-validation/index.js:20:28)
trustroots_1 |     at module.exports.schema.methods.trySave.proxyFn (/trustroots/node_modules/mongoose-beautiful-unique-validation/index.js:110:21)
trustroots_1 |     at /trustroots/node_modules/mongoose/lib/document.js:1813:19
trustroots_1 |     at proto.(anonymous function).handleError (/trustroots/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:40:22)
trustroots_1 |     at proto.(anonymous function).next_ (/trustroots/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:75:26)
trustroots_1 |     at fnWrapper (/trustroots/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:186:18)
trustroots_1 |     at /trustroots/node_modules/mongoose/lib/model.js:287:15
trustroots_1 |     at /trustroots/node_modules/mongoose/lib/model.js:188:14
trustroots_1 |     at /trustroots/node_modules/mongoose/lib/model.js:132:9
trustroots_1 |     at /trustroots/node_modules/mongoose/node_modules/mongodb/lib/collection.js:491:20
trustroots_1 |     at /trustroots/node_modules/mongoose/node_modules/mongodb/lib/collection.js:604:14
trustroots_1 |     at handleCallback (/trustroots/node_modules/mongoose/node_modules/mongodb/lib/utils.js:96:12)
trustroots_1 |     at /trustroots/node_modules/mongoose/node_modules/mongodb/lib/bulk/unordered.js:470:9
trustroots_1 |     at handleCallback (/trustroots/node_modules/mongoose/node_modules/mongodb/lib/utils.js:96:12)
trustroots_1 |     at resultHandler (/trustroots/node_modules/mongoose/node_modules/mongodb/lib/bulk/unordered.js:417:5)
trustroots_1 |     at commandCallback (/trustroots/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:936:9)
trustroots_1 |     at Callbacks.emit (/trustroots/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:116:3)
trustroots_1 |     at null.messageHandler (/trustroots/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:282:23)
trustroots_1 |     at Socket.<anonymous> (/trustroots/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:273:22)
trustroots_1 |     at emitOne (events.js:77:13)
trustroots_1 |     at Socket.emit (events.js:169:7)
trustroots_1 |     at readableAddChunk (_stream_readable.js:146:16)
trustroots_1 |     at Socket.Readable.push (_stream_readable.js:110:10)
trustroots_1 |     at TCP.onread (net.js:523:20)
```

**Comment by nicksellen** [comment]
This is the related issue https://github.com/matteodelabre/mongoose-beautiful-unique-validation/issues/17

**Comment by nicksellen** [comment]
It's fixed now in mongoose-beautiful-unique-validation v3.0.2

**Comment by simison** [comment]
Waiting for this to get merged; https://github.com/rschmukler/agenda/pull/334

**Comment by nicksellen** [comment]
I created branch for travis to use mongodb 3.2. It is currently passing.

https://github.com/Trustroots/trustroots/compare/mongodb-3.2

**Comment by simison** [comment]
Agenda got updated https://github.com/rschmukler/agenda/blob/master/History.md#090--2016-08-13

**Comment by simison** [comment]
done a while back
