### ISSUE TITLE
problem with fseventd on mac

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#623]
spin-off from #618

if you see problems with fseventd and gulp you can try this workaround: disable watch around this line: https://github.com/Trustroots/trustroots/blob/725ea112207b19fd837afed03e4b6e944425ac21/gulpfile.js#L533

may look like this:
```
[11:44:11] Starting 'watch'...
[11:44:11] Finished 'runNodemon' after 1.7 ms
[11:44:11] 'watch' errored after 6.14 ms
[11:44:11] Error: watching server.js,config/**/*.js,modules/*/server/**/*.js,worker.js,gulpfile.js,migrations/*.js: watch task has to be a function (optionally generated by using gu
lp.parallel or gulp.series)
    at Gulp.watch (/Users/guaka/trustroots/node_modules/gulp/index.js:28:11)
    at /Users/guaka/trustroots/gulpfile.js:171:8
    at taskWrapper (/Users/guaka/trustroots/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:396:14)
    at runBound (domain.js:409:12)
    at asyncRunner (/Users/guaka/trustroots/node_modules/async-done/index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)
[11:44:11] 'develop' errored after 13 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! trustroots@0.3.3 start:develop: `gulp develop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the trustroots@0.3.3 start:develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/guaka/.npm/_logs/2018-08-18T09_44_11_992Z-debug.log
Recieved shutdown signal, shutting down now...
[Worker] Stopping Agenda...
[Worker] Agenda stopped.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! trustroots@0.3.3 start: `concurrently --raw --kill-others --kill-others-on-fail 'npm run start:develop' 'npm run start:worker' 'npm run dashboard:mail'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the trustroots@0.3.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/guaka/.npm/_logs/2018-08-18T09_44_12_344Z-debug.log
```

**Comment by simison** [comment]
@guaka could you try with latest `master` and confirm that you don't see this anymore?

**Comment by guaka** [comment]
yeah master works now!
